[package]
name = "cuda-oxide-quant"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Quant cuda-oxide kernels"

[dependencies]
cuda-oxide.workspace = true
cuda-oxide-kernel-core = { workspace = true }

[dev-dependencies]
# Only testing / benchmark dependencies here.

[lints]
workspace = true

