[package]
name = "cuda-oxide-mla"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "MLA cuda-oxide kernels"

[dependencies]
cuda-oxide.workspace = true
cuda-oxide-kernel-core.workspace = true
cuda-oxide-kv-cache.workspace = true
cuda-oxide-quant.workspace = true

[dev-dependencies]
# Only testing / benchmark dependencies here.

[lints]
workspace = true

